runtime: nodejs16  # Käytä Node.js 16 versiota tai haluamaasi versiota

env_variables:
  DB_HOST: 'your-database-host'  # Määritä tietokannan host
  DB_USER: 'your-database-user'  # Tietokannan käyttäjätunnus
  DB_PASS: 'your-database-password'  # Tietokannan salasana
  DB_NAME: 'your-database-name'  # Tietokannan nimi
  PORT: '8080'  # Portti, jolla sovellus kuuntelee (Google Cloud käyttää yleensä porttia 8080)

handlers:
  - url: /static
    static_dir: public/  # Palveli staattiset tiedostot
